### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by pixelinkmedia** [azagaya/laigter#29]
Some suggestions for future updates...

1) Currently you can add lights, but cannot delete them afterwards. Need the ability to delete added lights

2) Creating, Edit and Saving of project settings so we can comeback and edit what we have made. From programmers viewpoint... you would just save a text file of the path to the image and all the settings.

FYI, tried the presets, but couldn't figure out how to get it to work. After creating a preset, I click save and Apply. Nothing happened. From a programming/user standpoint... this is kind of hidden away. I think just have a New, Open and Save project file would make more sense for users.... or make the Presets more front and canter and easier to use.
Some suggestions for future updates...

1) Currently you can add lights, but cannot delete them afterwards. Need the ability to delete added lights

2) Creating, Edit and Saving of project settings so we can comeback and edit what we have made. From programmers viewpoint... you would just save a text file of the path to the image and all the settings.

3) If you keep the export canvas function, a) change icon to something else beside an animation/video icon; b) The ability to edit the dimension (WxH) of the canvas.

**Comment by azagaya** [comment]
Hi! thanks for the suggestions.

About the lights, you can delete them with right-click.. i think it's on the tooltip.

About the project, yes, it is indeed needed, but i want to implement something more complex, like saving all textures and settings in a zip file (with extension changed to .laigter) and a JSon file to specify which texture corresponds to which settings. So you would be able to share projects among different computers... In the meantime, for using presets you have to check in the list at the left everything you want to save, and click "save". In the combo at the right, you select what preset you want to use, and in the list of texture, you select to which textures you want to apply all that. And then click apply.

**Comment by pixelinkmedia** [comment]
Presets... I did all that, doesn't seem to work for me.

1) I selected all the check boxes
2) Enter a name
3) Click the save button.
4) New preset shows up in dropdown
5) Close app down, reopen and load an image, select the preset
6) Click apply button.

I see no changes on the screen. Lights and everything are all the same.

Deleting deleting lights.
I right click and there is no popup menu to delete

**Comment by azagaya** [comment]
Sorry, i think i must explain this better or write a doc, untill i have proper project save/load.

For deleting lights, you should right click on the light you want to delete, in "add light mode". I mean, the add light button in the toolbar must be pressed, and then with left click you add lights, and with right click you delete lights.

Are you using presets to save the values of the settings for maps generations? that should work out of the box. Check if the sliders, when aplying the presets, change their values to the ones saved.
Are you using presets to save settings for ligths? So there's a gotcha there.
When i was asked to add multiple texture support, there was a problem because some users wanted same lights for all textures, and others wanted that each texture has its own lights. So i made both, and you select if you want lights per texture with a checbox. When you apply a setting containing lights settings, those will only be applied to the lights owned by the texture, so you will only see changes if "ligths per texture" checkbox is selected.

**Comment by azagaya** [comment]
Check this examples. May be they are not the most intuitive form, but it's what i could do...
![uno](https://user-images.githubusercontent.com/46932830/69987313-ffea4700-151d-11ea-9371-c01d8621790f.gif)
![dos](https://user-images.githubusercontent.com/46932830/69987418-3d4ed480-151e-11ea-9a4c-582294be9cc1.gif)

**Comment by pixelinkmedia** [comment]
Okay... i got the lights.

On the Presets... I was setting a preset and then closing the app. and trying to apply the preset to a new image
It doesn't work if you close the app.

The preset seems to only work within one session while the app is opened

**Comment by azagaya** [comment]
Thats stragne, It seems to work on my computer. It doesn't work at all or just for lights? Have you checked you have the "ligths per texture" when saving the preset and when applying it again?

**Comment by pixelinkmedia** [comment]
I am just testing lights.

**Comment by azagaya** [comment]
![tres](https://user-images.githubusercontent.com/46932830/69988648-cff07300-1520-11ea-872f-c4fe4681ee74.gif)

**Comment by azagaya** [comment]
Can you try to reproduce the steps i do in the gif?

**Comment by pixelinkmedia** [comment]
Okay... got it.
I have to check the Lights per texture option
Would not of known that.

I hate writing Help files.
However, you may need to do one soon.

Some people, like me do still read them because i know each program runs different.

**Comment by azagaya** [comment]
Well, having added project load/save in master branch, i think this issue is complete! Please tell me if you think this should be reopened.
