### ISSUE TITLE
issues with flipping complex normals

### ISSUE THREAD

**Issue by RandallMNixon** [azagaya/laigter#31]
I made a video showing what I am seeing. It's mostly when the normal is complex, but happened at different levels of the simple normal as well.

https://www.youtube.com/watch?v=SLHyL7vfgiQ

**Comment by azagaya** [comment]
Hi @RandallMNixon ! Thanks for the report and for taking the time to make a video of the issue. This issue is caused that a bug that makes the normals generated by bum controls not to be updated unless you modify the "distance" slider. Please, try to modify "distance" slider AFTER you check the invert checkbox, and the normals will be fixed.
This bug was introduced in 1.8, so you could also use 1.7, and shouldnt be present. 
Please tell me if this workarround works for you. Thanks again!

**Comment by RandallMNixon** [comment]
@azagaya Thank you for a quick response, and I apologize for my later response, I was able to test 1.7 and 1.8 on both Windows 10 and Ubuntu 18.04 LTS and found your explanation to be accurate on both systems. Giving more information I also had 1.8 freeze and terminate on both systems while causing the bug to appear and attempting to work past it.

**Comment by azagaya** [comment]
@RandallMNixon 

> Giving more information I also had 1.8 freeze and terminate on both systems while causing the bug to appear and attempting to work past it.

Ohh that sounds bad... i'll try to replicate this.

**Comment by RandallMNixon** [comment]
In testing 1.8.1, I was not able to reproduce this bug in either form. Performance is very good! No stutters or freezes and normals flip as expected in the same scenarios 1.8 failed at.

**Comment by azagaya** [comment]
Cool! thanks for testing! i think i can close this issue for now. If you find something else, feel free to write here and i'll reopen it.
Tahnks!
