### ISSUE TITLE
Look for another Image processing library (or use Qt's functions)

### ISSUE THREAD

**Issue by azagaya** [azagaya/laigter#4]
The idea is to replace opencv for a lighter and easier to compile in multiple platforms library.
In theory, we just need a distance transform function, and common color manipulation features.

If anyone cames up with any idea, please comment!

**Comment by leiserfg** [comment]
Maybe you can use CImg which is a header-only library.

**Comment by azagaya** [comment]
Thanks for the suggestions! Yes, it looks like the best option right now... the only thing about CImg, is that sometime in the future i wanted to release Laigter under MIT license, so using a MIT compatible library would be best for that. But for that moment i would have also to replace Qt, so it wont be the worst problem to also change the image library again. 
I will do some tests with CImg as soon as i have some free time.. have you used it before?

**Comment by leiserfg** [comment]
Well, you can use Qt in a MIT project,  cause it's is LGPL. I used CImg some years ago, but I have not done C++ for years.

**Comment by azagaya** [comment]
Yes, i could use LGPL license, but i must provide a way to the user to change the libraries or something (i know little obout licenses, i may be wrong). And some Qt modules are only under GPL (i'm not using them right now anyways). So, i could also use CImg in a MIT licensed software under the same conditions of a LGPL one?

**Comment by leiserfg** [comment]
You can copy the `CImg.h` file and keep the Apache 2 license for it, and then use MIT for your code.

**Comment by azagaya** [comment]
Thanks for the help! I'll try to do some tests!

**Comment by Gnumaru** [comment]
I am not a lawyer and this is not legal advice. In the Qt download page (qt.io/download) there is a comparison between the commercial and the open source licensing schemes. In the open source version only some things are GPL only instead of LGPL. As long as you use only the LGPL things AND you only do dynamic linking instead of static linking AND you do not include source files or copy code from the Qt framework libraries inside your codebase, you could use Qt for closed source commercial applications even when using the "open source" licensing schemes.

> Yes, i could use LGPL license, but i must provide a way to the user to change the libraries or something (i know little obout licenses, i may be wrong).

The "changing libraries" thing, as far as I know, is just a consequence of dynamic linking instead of static linking. When dynamic linking a library one can always exchange a .dll (or .so) for another as long as they have identical symbol tables entries for the symbols used by the linking binary, that is, all the exported symbols in the binary used by the app have the same identifier (name) in both binaries. One's app just uses the library as a black box, inputing and outputing data in/from it, the reason why the the app is not a derivative work of the LGPL library. When static linking, all the compiled code from the static libraries is embeded in the resulting binary, thus making it a "derivative work" of the static library, that's the reason why static linking an LGPL library automaticaly makes your code (L)GPL too. I also don't know much about legal stuff and open source licensing, but I think LGPL was created because the GPL terms were unclear whether dynamic linking a library was acounted as a derivative work or not and would trigger or not the GPL viral effect, whereas LGPL is explicitly about dynamic linking (I didn't read the LGPL or GPL licenses, I'm only making asumptions here).

**Comment by azagaya** [comment]
Hi! thanks for the comments. I think static linking is allowed in LGPL, but you must provide the *.o file of the compilation process along with the binary, so the user can link it to another library. And you must give a procedure to achieve this change. Also, i've read somewhere in Qt's web, that if you are not using GPL or LGPL license, then you must provide the source of the Qt libraries used (you can not distribute your code, but you must distribute the version of Qt you used) and a link to Qt's repo is not enough. Anyways, that would not affect Laigter as it's open source... i just don't get if i can use on MIT license (that's why i choose GPL for Laigter in first place). Anyways, if that's the case, i think i should try to embed all the algorithms for normals calculations in one library, and release that library as MIT, as what other people wants to use is int their own projects is that, not the full app.

**Comment by leiserfg** [comment]
By the way, if you are planing to use CImg, take a look at 
https://github.com/c-koi/gmic-qt/blob/master/src/ImageConverter.cpp
gmic uses CImg internally.

**Comment by Gnumaru** [comment]
I just watched this video. Its from the Qt youtube channel, with a real lawyer:

https://www.youtube.com/watch?v=lSYDWnsfWUk

And I also read the LGPLv3 text

https://www.gnu.org/licenses/lgpl-3.0.txt

And I searched for some things on the gpl faq

https://www.gnu.org/licenses/gpl-faq.html


It seems that:

* Regardless if you are making a closed source or open source software, you do not necessarily need to bundle binaries and it's source code together. Providing a download link for the source code is enough to comply with the license terms. If this was not the case, every open source software out there should come with the source bundled together, wich is not the case. For example, Blender is open source but the blender installer for windows does not come with the source code bundled together. Open source software binary bundles, in fact, always never comes with the source. When you apt-get install something on debian and derivatives, the deb package contains only the binaries and you must use apt-get source to get another different package that comes only with the sources, without the binaries, that is, two separate packages.
* If you are using dynamic linking with lgpl software you have almost nothing to worry. You must state that you used an LGPL library, provide both the GPL and LGPL licenses and provide the download link for the LGPL source code for the library you used. You do not need to provide object files for relinking because to switch libraries when using dynamic linkage the user only needs to remove the library file from the library path (wich includes the application folder in windows) and put there another file with the same file name and symbol table.
* It seems I was wrong about static linking. You can also static link **and** make a closed source app **as long as** you provide the object files for the application so that the user can relink the application. Of course provinding the source code is also an option, but the static linkage in itself does not make the app become (L)GPL.

The only thing I was getting trouble to understand was about including code from header files. At first it seemed that, when you are using a header file containing any inline functions that have more than 10 lines of code, this would make your code also lgpl. Here is the excerpt

```
3. Object Code Incorporating Material from Library Header Files.

  The object code form of an Application may incorporate material from
a header file that is part of the Library.  You may convey such object
code under terms of your choice, provided that, if the incorporated
material is not limited to numerical parameters, data structure
layouts and accessors, or small macros, inline functions and templates
(ten or fewer lines in length), you do both of the following:

   a) Give prominent notice with each copy of the object code that the
   Library is used in it and that the Library and its use are
   covered by this License.

   b) Accompany the object code with a copy of the GNU GPL and this license
   document.
```

But after carefull reading one can realize that the phrase
```
(...)
You may convey such object code under terms of your choice, provided that, if the incorporated material **is not limited** to numerical parameters, data structure layouts and accessors, or small macros, inline functions and templates (ten or fewer lines in length), **you do both of the following:** (...)
```
is equivalent to 
```
(...)
If the incorporated material **is limited** to numerical parameters, data structure layouts and accessors, or small macros, inline functions and templates (ten or fewer lines in length), **then** you do not need to do anything. But if it is not the case, you (still) may convey such object code under terms of your choice (like closed sourcing terms), provided that you do both of the following: (...)
```
That is, event if a header file has more than ten lines of inline code or template code, you only become obligated  to state that your app makes use of LGPL code from header files for that library and that that included header file code is licensed under the terms of LGPL, and then you must also include the license itself.

So, it seems it is safe to put Laigter under MIT and still comply with the terms of Qt's LGPL.

**Comment by azagaya** [comment]
Great News! I'll always doubted about that, because other open source MIT projects always neglected to use LGPL libraries, so i thought it was incompatible.
We should make a sway to MIT some time in near future.

**Comment by azagaya** [comment]
Hey, if you are interested in discussing what path should Laigter follow, and continue contributing, perhaps i could open a Discord server, so conversation is more fluid. What do you think? I write this here because i have no other way to contact you!

**Comment by ffyhlkain** [comment]
+1 for the discord server. Easy to setup, nice for quick discussions and easier to gather interested people.

**Comment by azagaya** [comment]
Here it is!
https://discord.gg/KdnkhE

**Comment by azagaya** [comment]
If someone is interested, im slowly replacing opencv with Qt native image manipulation. It is supposed to be slower, but we can care about performance later, trying with smaller lib.

**Comment by azagaya** [comment]
I replaced OpenCV with CImg.. it works for now, but the drop in performance is noticeable. Closing this for now.
