### ISSUE TITLE
Blank window on Linux

### ISSUE THREAD

**Issue by avahe-kellenberger** [azagaya/laigter#98]
I cloned and built the project according to the README, and laigter is just a blank window. Here's the terminal output:
```
 ./laigter
QMetaObject::connectSlotsByName: No matching signal for on_pushButton_clicked()
QOpenGLShaderProgram::attributeLocation(aPos): shader program is not linked
QOpenGLShaderProgram::attributeLocation(aPos): shader program is not linked
QOpenGLShaderProgram::attributeLocation(aTexCoord): shader program is not linked
QOpenGLShaderProgram::attributeLocation(aTexCoord): shader program is not linked
QObject::disconnect: Unexpected nullptr parameter
QObject::disconnect: Unexpected nullptr parameter
QImage::scaled: Image is a null image
QObject::disconnect: Unexpected nullptr parameter
```

I assume this may be an incompatibility with Qt? I'm on Arch Linux, the most recent version of `qt5-base` currently is `qt5-base 5.15.10+kde+r158-1`.

If you have any thoughts/ideas to debug the problem I'd appreciate it. Thanks!

**Comment by azagaya** [comment]
Hi,
you dont see anything, not even the UI? Or you just dont see the rendering?
Those message in the console are not critical. It should work anyways.

**Comment by avahe-kellenberger** [comment]
Nothing at all, the window just isn't rendering any contents.

**Comment by azagaya** [comment]
Can you share me your PC specs? Have you tried the appimage in the releases?

**Comment by avahe-kellenberger** [comment]
I've also tried the appimage with the same result.

```
avahe@throne 
------------ 
OS: Arch Linux x86_64 
Kernel: 6.1.55-1-lts 
Resolution: 1920x1080 
WM: nimdow 
Theme: Ant-Dracula [GTK2/3] 
Icons: breeze-dark [GTK2/3]
CPU: AMD Ryzen 9 7950X (32) @ 4.500GHz 
GPU: AMD ATI Radeon RX 6800/6800 XT / 6900 XT 
Memory: 4474MiB / 31828MiB 
```

**Comment by leombrunk** [comment]
I ran into this issue and did some testing, it seems to be an issue with the var `need_to_update`  when it checks for it in force_update.

With the check present I can only update the display by clicking on or around the image. Otherwise opening the program for the first time or changing windows leads to a blank screen. It's not until I click on or around the image that the display updates. And then clicking buttons/sliders/tabs makes no update to the display until I again click on or around the image.

I am also using an AMD gpu (mesa driver) and a window manager so this maybe related
WM: i3
CPU: AMD Ryzen 7 5825U with Radeon Grap
GPU: AMD ATI 04:00.0 Barcelo

My solution for now is to remove the check for need_to_update in force_update so that it just always runs update() but I'm sure that check exists for performance reasons or something so I think a real solution is still needed.

**Comment by Raiguri** [comment]
Still not fixed :(

**Comment by azagaya** [comment]
@Raiguri is been very hard for me to fix this because I've never been able to reproduce on my side sadly.
If i ever reproduce it ill will work on a fix.

The workarround of removing need_to_update wont be viable for everyone as it increases the cpu usage a lot.
